connectors:
  percentage-service:
    url: ${PERCENTAGE_SERVICE_URL}
    path: ${PERCENTAGE_GET_SERVICE_PATH}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database: default
    open-in-view: false
redisson:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}