spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

bucket4j:
  enabled: true
  filters:
    - cache-name: cache
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 3
              time: 60
              unit: seconds
  cache-to-use: redis-springdata